project:
  type: website

website:
  title: "Zoning's Relation To Rent In American Municipalities"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: sources.qmd
        text: Sources
      - href: additional_graphs.qmd
        text: Additional Graphs

      

format:
  html:
    theme: minty
    css: styles.css
    toc: true



